[workspace]
resolver = "2"
members = [
    "solutions/*"
]

[workspace.dependencies]
anyhow = "1.0.75"
nom = "7.1.3"
regex = "1.10.2"
rayon = "1.8.0"
itertools = "0.12.0"
fxhash = "0.2.1"
image = "0.24.7"