init day:
    #!/usr/bin/env bash
    padday=`printf "%02d" {{day}}`
    cp -r solutions/_template solutions/day${padday}
    sed -i '' -e "s/__day__/${padday}/g" solutions/day${padday}/Cargo.toml
    sed -i '' -e "s/__day__/${padday}/g" solutions/day${padday}/src/bin/part1.rs
    sed -i '' -e "s/__day__/${padday}/g" solutions/day${padday}/src/bin/part2.rs

check day:
    cargo fmt -p day$(printf "%02d" {{day}})
    cargo clippy -p day$(printf "%02d" {{day}})
    just test {{day}} 1
    just run {{day}} 1
    just test {{day}} 2
    just run {{day}} 2

test day part: 
    cat data/test/$(printf "%02d" {{day}}).txt \
        | cargo run \
            -p day$(printf "%02d" {{day}}) \
            --bin part{{part}}

run day part:
    cat data/$(printf "%02d" {{day}}).txt \
        | cargo run --release \
            -p day$(printf "%02d" {{day}}) \
            --bin part{{part}}

time day part:
    hyperfine --warmup 3 'just run {{day}} {{part}}'