[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc"
path = "src/lib.rs"

[dependencies]
bitvec = "1.0.1"
im = "15.1.0"
image = "0.24.5"
itertools = "0.10.5"
regex = "1.7.0"
